version: 0.2

env:
  variables:
    DEFAULT_VERSION_TYPE: "minor"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - "echo 'Installing dependencies...'"
      - "npm install"

  pre_build:
    commands:
      - "echo 'Logging into CodeArtifact...'"
      - "aws codeartifact login --tool npm --domain ledgerlink-domain --domain-owner 273491477087 --repository ledgerlink --region us-east-1"
      - "echo 'Environment Variables Debug:'"
      - "echo 'VERSION_TYPE from pipeline:' \"$VERSION_TYPE\""
      - "echo 'DEFAULT_VERSION_TYPE:' \"$DEFAULT_VERSION_TYPE\""
      - "echo 'Determining final version type...'"
      - |
        if [ -n "$VERSION_TYPE" ] && [[ "$VERSION_TYPE" =~ ^(major|minor|patch)$ ]]; then 
          FINAL_VERSION_TYPE="$VERSION_TYPE"; 
        else 
          FINAL_VERSION_TYPE="$DEFAULT_VERSION_TYPE"; 
        fi
      - "echo 'Final VERSION_TYPE being used:' \"$FINAL_VERSION_TYPE\""
      - "echo 'Getting current published version from CodeArtifact...'"
      - "CURRENT_VERSION=$(npm view @ledgerlink/hello-world-lib version 2>/dev/null || echo '1.0.0')"
      - "echo 'Current published version:' $CURRENT_VERSION"
      - "echo 'Setting package.json to current published version...'"
      - "npm version $CURRENT_VERSION --no-git-tag-version --allow-same-version"
      - "echo 'Bumping' $FINAL_VERSION_TYPE 'version...'"
      - "NEW_VERSION=$(npm version $FINAL_VERSION_TYPE --no-git-tag-version)"
      - "echo 'New version to be published:' $NEW_VERSION"

  build:
    commands:
      - "echo 'Publishing to CodeArtifact...'"
      - "npm publish"

artifacts:
  files:
    - '**/*'