version: 0.2

env:
  variables:
    DEFAULT_VERSION_TYPE: "minor"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - "set -e"
      - "echo 'Logging into CodeArtifact...'"
      - "aws codeartifact login --tool npm --domain ledgerlink-domain --domain-owner 273491477087 --repository ledgerlink --region us-east-1"

      - "echo 'Configuring .npmrc to use CodeArtifact with fallback to npmjs.org...'"
      - "echo '@ledgerlink:registry=https://ledgerlink-domain-273491477087.d.codeartifact.us-east-1.amazonaws.com/npm/ledgerlink/' > .npmrc"
      - "echo 'registry=https://ledgerlink-domain-273491477087.d.codeartifact.us-east-1.amazonaws.com/npm/ledgerlink/' >> .npmrc"
      - "echo '//ledgerlink-domain-273491477087.d.codeartifact.us-east-1.amazonaws.com/npm/ledgerlink/:always-auth=true' >> .npmrc"

      - "echo 'Installing axios (should fallback to npmjs if not in CodeArtifact)...'"
      - "npm install axios"

      - "echo 'Installing other dependencies...'"
      - "npm install"

  pre_build:
    commands:
      - "set -e"
      - "if [ -n \"$VERSION_TYPE\" ] && [[ \"$VERSION_TYPE\" =~ ^(major|minor|patch)$ ]]; then FINAL_VERSION_TYPE=\"$VERSION_TYPE\"; else FINAL_VERSION_TYPE=\"$DEFAULT_VERSION_TYPE\"; fi"
      - "echo \"Final version type: $FINAL_VERSION_TYPE\""
      - "npm version"
      - "CURRENT_VERSION=$(npm view @ledgerlink/hello-world-lib version 2>/dev/null || echo '1.0.0')"
      - "echo \"Current version: $CURRENT_VERSION\""
      - "echo 'Syncing package.json to current version...'"
      - "npm version \"$CURRENT_VERSION\" --no-git-tag-version --allow-same-version"
      - "echo \"Bumping $FINAL_VERSION_TYPE version...\""
      - "NEW_VERSION=$(npm version \"$FINAL_VERSION_TYPE\" --no-git-tag-version)"
      - "echo \"New version: $NEW_VERSION\""

  build:
    commands:
      - "echo 'Publishing to CodeArtifact...'"
      - "npm publish"

artifacts:
  files:
    - '**/*'
